spring:
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ide?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  #elasticsearch config
#  data:
#    elasticsearch:
#      cluster-name: es
#      cluster-nodes: 127.0.0.1:9300
#      repositories:
#        enabled: true

#mybatis config
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.online_program.entity

server:
  address: 127.0.0.1
  port: 8081
  error:
    path: ./

#log config
logging:
  file: ./ide-8081.log
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger-->> %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger-->> %msg%n'
  level:
    root: info
    com.example.online_program: debug



