spring:
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://182.92.107.205:3306/ide?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.online_program.entity

server:
  address: 127.0.0.1
  port: 8080
  error:
    path: ./log/

#log config
logging:
  file: ./log/ide-dev-8080.log
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger-->> %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger-->> %msg%n'

  level:
    root: info
    com.example.online_program: debug

  #elasticsearch config
elasticsearch:
    node1:
      host: 182.92.107.205
      port: 9200
      scheme: http
    node2:
      host: 182.92.107.205
      port: 9201
      scheme: http
    index: ide_code_index
    table: ide_code_table
#default port : ssh=22，ftp=21
sftp:
  client:
    host: 182.92.107.205
    port: 22
    userName: root
    passWord: j1535284.
    desDirPath: /pydir/


